DEFAULT_MAGENTO_VALUES: dict[str, object] = {
    "attribute_set_id": "Gemstones",
    "status": "Disabled",
    "tax_class_id": "Jewellery Semiprecious",
    "vendor": "GP",
    "offer_type": "Loose Gemstone",
    "offers": "Express Dispatch",
    "gem_composition": "Natural",
    "return_policy": "10 Day Money-Back Returns*",
    "dimension_type": "Not Calibrated",
    "dispatch_days": "0 Business Days (+5 days for typical Jewellery; +14 days for Bracelet/Gold/CZ/Diamond Items)",
    "shipping_days": 0,
    "show_pricing_table": "No",
    "callfor_price_wanto_show": "No",
    "callfor": "No",
    "call_for_price_text": "Call For Price",
    "redirect_select_for_quality": 0,
    "calibrated_size_range": ",",
    "beads_size": ",",
    "hole": ",",
    "quality_grade": ",",
    "strands": ",",
    "dimension_approx": ",",
    "product_type": "Single Stone",
}
