"""
Production Magento/GemPundit column registry.

`FINAL_MAGENTO_MODEL_COLUMNS` is derived from the user's final Magento catalogue model
(`/mnt/data/report240426.csv`, received 2026-04-24). Preserve names exactly, including
legacy spellings such as `comment_explation` and `gemstone_benifits_new`.
"""

FINAL_MAGENTO_MODEL_COLUMNS: tuple[str, ...] = (
    "attribute_set_id",
    "sku",
    "name",
    "meta_title",
    "url_key",
    "sku_for_vendor_product",
    "treatment",
    "carat_weight",
    "classification",
    "cutting_style",
    "dimensions",
    "j_colour",
    "name2",
    "offers",
    "vendor_id",
    "weight_ratti",
    "shipping_days",
    "hsn_code",
    "price",
    "special_price",
    "weight_carat",
    "price_per_carat",
    "weight_sort1",
    "status",
    "tax_class_id",
    "gemstone",
    "gem_composition",
    "shape",
    "certification",
    "return_policy",
    "colour",
    "cut",
    "dimension_type",
    "dispatch_days",
    "gemstone2",
    "vendor",
    "offer_type",
    "origin",
    "product_type",
    "description",
    "short_description",
    "comment_explation",
    "description2",
    "qty",
    "is_in_stock",
    "gemstone3",
    "image",
    "small_image",
    "thumbnail",
    "invoice_id",
    "news_from_date",
    "news_to_date",
    "stickers",
    "callfor",
    "quality_config_gem",
    "redirect_select_for_quality",
    "select_for_quality",
    "mainproduct_forjewlrypage",
    "gemstone2_type",
    "price_per_carat_range",
    "metal_config",
    "ideal_design",
    "price_for_jewelry",
    "promotion_baseprice_jewlery",
    "product_discount_percentage",
    "promotion_discount_price",
    "specific_gravity",
    "refractive_index",
    "show_pricing_table",
    "callfor_price_wanto_show",
    "automatic_video_link",
    "call_for_price_text",
    "calibrated_size_range",
    "beads_size",
    "hole",
    "beads_in_strand",
    "length_inches",
    "quality_grade",
    "strands",
    "dimension_approx",
    "arrangement_type",
    "length_cm",
    "how_to_wear",
    "certificate_number1",
    "verified_certificateimage",
    "verified_certificateimage1",
    "additional_certification",
    "price_range",
    "gemstone_benifits_new",
    "product_category_type",
)

MAGENTO_EXPORT_COLUMNS: tuple[str, ...] = FINAL_MAGENTO_MODEL_COLUMNS

SOURCE_ALIASES: dict[str, str] = {
    "a": "source_internal_id",
    "a.1": "source_image_path",
    "a.2": "automatic_video_link",
    "_attribute_set": "attribute_set_id",
    "certificate_number": "certificate_number1",
    "benefits": "gemstone_benifits_new",
    "gemstone_benefits_new": "gemstone_benifits_new",
    "comment_explanation": "comment_explation",
    "main_image": "image",
}

STAFF_TEMPLATE_COLUMNS: tuple[str, ...] = (
    "sku",
    "sku_for_vendor_product",
    "name",
    "gemstone",
    "origin",
    "treatment",
    "carat_weight",
    "weight_ratti",
    "shape",
    "colour",
    "cut",
    "cutting_style",
    "dimensions",
    "dimension_type",
    "certification",
    "certificate_number1",
    "price",
    "special_price",
    "qty",
    "vendor",
    "vendor_id",
    "hsn_code",
    "dispatch_days",
    "shipping_days",
    "return_policy",
    "image",
    "small_image",
    "thumbnail",
    "verified_certificateimage",
    "verified_certificateimage1",
    "automatic_video_link",
    "short_description",
    "description",
    "description2",
    "meta_title",
    "url_key",
    "classification",
    "gemstone2",
    "gemstone2_type",
    "gemstone3",
    "product_category_type",
    "gemstone_benifits_new",
    "specific_gravity",
    "refractive_index",
)

ADMIN_ONLY_COLUMNS: tuple[str, ...] = (
    "attribute_set_id",
    "status",
    "tax_class_id",
    "offers",
    "offer_type",
    "stickers",
    "callfor",
    "quality_config_gem",
    "redirect_select_for_quality",
    "select_for_quality",
    "mainproduct_forjewlrypage",
    "metal_config",
    "ideal_design",
    "price_for_jewelry",
    "promotion_baseprice_jewlery",
    "product_discount_percentage",
    "promotion_discount_price",
    "show_pricing_table",
    "callfor_price_wanto_show",
    "call_for_price_text",
)
